// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

var defaultState = /* record */[
  /* count */0,
  /* show */true
];

function stateReducer(state, action) {
  if (action) {
    return /* record */[
            /* count */state[/* count */0],
            /* show */!state[/* show */1]
          ];
  } else {
    return /* record */[
            /* count */state[/* count */0] + 1 | 0,
            /* show */state[/* show */1]
          ];
  }
}

function createMessage(count) {
  return "You've clicked this " + (String(count) + " times(s)");
}

function Component2(Props) {
  var greeting = Props.greeting;
  var match = React.useReducer(stateReducer, defaultState);
  var dispatch = match[1];
  var state = match[0];
  var message = createMessage(state[/* count */0]);
  var match$1 = state[/* show */1];
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* Click */0);
                    })
                }, message), React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* Toggle */1);
                    })
                }, "Toggle greeting"), match$1 ? greeting : null);
}

var make = Component2;

exports.defaultState = defaultState;
exports.stateReducer = stateReducer;
exports.createMessage = createMessage;
exports.make = make;
/* react Not a pure module */
