// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$ReactHooksTemplate = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(App$ReactHooksTemplate.make, { }), "app-entry-point");

/*  Not a pure module */
