FROM matthewjamesbriggs/circleci-node-stretch-lfs:v001

RUN sudo apt-get update && sudo apt-get install -y \
    curl \
    apt-transport-https && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash

RUN sudo apt-get update && sudo apt-get install -y \
    openssh-client \
    git-lfs && \
    git lfs install

