// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE

import * as App$Mjb from "./app.bs.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$Mjb.make(/* array */[])), "root");

export {
  
}
/*  Not a pure module */
