// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Game$ReactTemplate = require("./Game.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Game$ReactTemplate.make("Hello! Click this text.", /* array */[])), "root");

/*  Not a pure module */
