// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var card = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.alignItems(Css.stretch),
          /* :: */[
            Css.backgroundColor(Css.white),
            /* :: */[
              Css.boxShadow(undefined, Css.px(3), Css.px(5), undefined, undefined, Css.rgba(0, 0, 0, 0.3)),
              /* :: */[
                Css.unsafe("-webkit-overflow-scrolling", "touch"),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var title = Css.style(/* :: */[
      Css.fontSize(Css.rem(1.5)),
      /* [] */0
    ]);

function actionButton(disabled) {
  return Css.style(/* :: */[
              Css.background(disabled ? Css.darkgray : Css.white),
              /* :: */[
                Css.color(Css.black),
                /* :: */[
                  Css.border(Css.px(1), Css.solid, Css.black),
                  /* :: */[
                    Css.borderRadius(Css.px(3)),
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

var ol = Css.style(/* :: */[
      Css.unsafe("padding-left", "30px"),
      /* [] */0
    ]);

var ul = Css.style(/* :: */[
      Css.unsafe("padding-left", "30px"),
      /* [] */0
    ]);

var Styles = /* module */[
  /* card */card,
  /* title */title,
  /* actionButton */actionButton,
  /* ol */ol,
  /* ul */ul
];

Css.$$global("body", /* :: */[
      Css.fontSize(Css.px(14)),
      /* [] */0
    ]);

exports.Styles = Styles;
/* card Not a pure module */
