// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var centuryGothic = "Century Gothic";

var futura = "Futura";

var sansSerif = "sans-serif";

function quote(str) {
  return "\"" + (str + "\"");
}

var fontFamiliesGlobal_001 = /* :: */[
  futura,
  /* :: */[
    sansSerif,
    /* [] */0
  ]
];

var fontFamiliesGlobal = /* :: */[
  centuryGothic,
  fontFamiliesGlobal_001
];

var fontFamiliesGlobalStr = List.fold_left((function (a, b) {
        return quote(a) + (", " + quote(b));
      }), List.hd(fontFamiliesGlobal), List.tl(fontFamiliesGlobal));

var fontGlobalStr = Pervasives.string_of_float(14.0) + ("px " + fontFamiliesGlobalStr);

function fontGlobal(param) {
  return {
          font: fontGlobalStr
        };
}

var fontSizeGlobalPx = 14.0;

exports.centuryGothic = centuryGothic;
exports.futura = futura;
exports.sansSerif = sansSerif;
exports.quote = quote;
exports.fontFamiliesGlobal = fontFamiliesGlobal;
exports.fontFamiliesGlobalStr = fontFamiliesGlobalStr;
exports.fontSizeGlobalPx = fontSizeGlobalPx;
exports.fontGlobalStr = fontGlobalStr;
exports.fontGlobal = fontGlobal;
/* fontFamiliesGlobalStr Not a pure module */
