// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function LeftSide(Props) {
  return React.createElement("div", {
              className: "nav col-1"
            });
}

var make = LeftSide;

exports.make = make;
/* react Not a pure module */
