// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function StandardPage(Props) {
  return React.createElement("div", {
              id: "flksjdf"
            }, React.createElement("div", {
                  className: "leftcol"
                }), React.createElement("div", {
                  className: "maincol"
                }));
}

var make = StandardPage;

exports.make = make;
/* react Not a pure module */
