// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

Css.$$global("*", /* :: */[
      Css.boxSizing(Css.borderBox),
      /* [] */0
    ]);

var body = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.minHeight(Css.vh(100)),
        /* :: */[
          Css.flexDirection(Css.row),
          /* :: */[
            Css.margin(Css.px(0)),
            /* [] */0
          ]
        ]
      ]
    ]);

var col1 = Css.style(/* :: */[
      Css.background(Css.hex("#D7E8D4")),
      /* [] */0
    ]);

exports.body = body;
exports.col1 = col1;
/*  Not a pure module */
